components/registration/default-registration-form.html, components/registration/registration-controller.js
Make sure the registration controller and data entry controller works
the same way
=> save data for radio sluggishness fixed in data entry on registration page

components/dataentry/dataentry-controller.js
The the event status used not to get updated in the model. This caused
problems for rule execution.
=> Update event status in model

README.md, components/dataentry/new-event-controller.js, components/dataentry/new-event-menu.html, components/dataentry/new-event.html, components/registration/registration-controller.js, i18n/i18n_app.properties
Added referral functionality for the tracker-capture-app, some of the code was already there and some has been imported from HRHR/palestine project.
=> Added referral functionallity

components/relationship/relationship-controller.js, components/teiadd/tei-add.html, scripts/services.js
- Fix for relationships not being stored nor fetched when the browser refreshed.
https://jira.dhis2.org/browse/DHIS2-2009
=> Fix for relationships not being persistent

styles/style.css
=> Fixed events in timeline not aligning correctly.

views/tei.html
- Fix for where you could not sort TEIs when in the relationship module.
**Before:**
**After:**
=> Fix for sorting TEIs in relationship module

components/dataentry/event-details.html, components/registration/registration-controller.js
- In the case where a program stage is displayed in the registration phase, the report date will auto-fill (with enrollment date) when the user tabs/selects the program stages report date field.
- https://jira.dhis2.org/browse/DHIS2-378
=> Added auto-fill date

components/dataentry/new-event-controller.js
- Fixed a bug where when adding an event or scheduling an event the system would suggest the last program stage instead of the first which is the most likely program stage to be selected next.
- https://jira.dhis2.org/browse/DHIS2-2012
=> Fixed bug where sort order was not working as intended

components/dataentry/dataentry-tabular-layout.html
- Added a referral button for the tabular data entry widget.
=> Added referral button for the tabular data entry widget

components/dataentry/dataentry-controller.js, components/dataentry/event-details.html, i18n/i18n_app.properties, styles/style.css
- **NOTE:** This change is dependent on also updating the d2-tracker with this code: https://github.com/dhis2/d2-tracker/pull/2
- https://jira.dhis2.org/browse/DHIS2-2075
- Hidd the report date clear date button.
- Also added a message to the user when they try to clear the report date manually (with the backspace key), to give an explanation to the user.
=> Ensured that report date can NOT be cleared

scripts/controllers.js, scripts/services.js
https://jira.dhis2.org/browse/DHIS2-1721
=> Fix show-hide column in list.

components/registration/default-registration-form.html, i18n/i18n_app.properties
- **NOTE:** This change is dependant on this PR: https://github.com/dhis2/d2-tracker/pull/6
- This change adds a feedback (red text under the input field) to the user when the URL is invalid.
=> Added URL validation

components/dataentry/inner-form.html, components/dataentry/section-inner-form.html
- Gives the user feedback in form of a red text under the input field that the URL is invalid.
- Also fixed an issue where data would not be saved.
=> Added URL validation on several URL input fields.

index.ejs
Use the header bar from d2-ui v28.0.2
=> Update header bar

index.ejs, webpack.config.js
See the identical PR for master: #86
=> Fix header bar for 2.28

index.ejs, webpack.config.js
Use d2-ui v28.0.3, and specify the correct API base path
=> Fix the header bar

components/dataentry/dataentry-controller.js, components/registration/registration-controller.js
- minDate was not converted to the correct calendar format.
- This fix is dependant on https://github.com/dhis2/d2-tracker/pull/8
=> Fixed bug where Calendar would not work with certain calendars (Islamic and Persian).

components/dataentry/default-form.html, components/dataentry/section-inner-form.html
- Fixed a bug when first program stage was displayed during registration.
- The bug was related to the data element "DATE" trying to use a method that was not available in the current scope while registering.
- Also fixed a related issue concerning if a "DATE" element is required, was not working properly but should be working now.
=> Section form in registration bug fix v28

components/dataentry/default-form.html, components/dataentry/section-inner-form.html
- Fixed a bug when first program stage was displayed during registration.
- The bug was related to the data element "DATE" trying to use a method that was not available in the current scope while registering.
- Also fixed a related issue concerning if a "DATE" element is required, was not working properly but should be working now.
=> Program stage with sections during registration fix

components/enrollment/enrollment-controller.js
- https://jira.dhis2.org/browse/DHIS2-1763
- When deleting an enrollment user is redirected back to search.
=> Deleting enrollment improvement

components/dashboard/dashboard-controller.js, components/dashboard/dashboard.html, components/dataentry/dataentry-tabular-layout.html, components/dataentry/dataentry.html, components/enrollment/enrollment.html, components/messaging/messaging.html, components/notes/notes.html, components/profile/profile.html, components/relationship/relationship.html, components/report/tei-report.html, components/rulebound/rulebound.html, components/selected/selected.html, i18n/i18n_app.properties, scripts/services.js
- https://jira.dhis2.org/browse/DHIS2-687
- The admin can lock a layout for each specific program. When a user enters the tracker-capture dashboard the system will check if the layout of the selected program is locked. If it is, the default layout (set by admin) will be used instead of a potential custom layout the user himself has set.
=> Give admin the ability to lock dashboard layouts

components/dataentry/inner-form.html, components/dataentry/section-inner-form.html, components/registration/default-registration-form.html, styles/style.css
- Users are now able to use the USERNAME data element and tracked entity attribute.
- Requires newest instance of d2-tracker.
=> USERNAME data element

components/dataentry/inner-form.html, components/dataentry/section-inner-form.html, components/home/lists/lists-controller.js, components/registration/default-registration-form.html, components/registration/registration-controller.js, components/registration/registration.html, i18n/i18n_app.properties, views/tei-list.html
- Adds the ability to user images as data-elements and tracked entity attributes.
- Needs update in d2-tracker: https://github.com/dhis2/d2-tracker/pull/16.
=> Image data-element and tracked entity attribute

components/enrollment/enrollment-controller.js
- When a TEI is enrolled in a new program the system would enrol the TEI and go back to the program the user entered the dashboard with. Now when a TEI is enrolled, the selected program stays and does not go back to the program you entered with.
=> Stoped program switch

components/registration/registration-controller.js
https://jira.dhis2.org/browse/DHIS2-4176
` if(attribute.value !== '' && attribute.value)`  return false for value = zero
=> [DHIS2-4176] Fix bug saving zero attribute value.

components/registration/registration-controller.js, package-lock.json, package.json
backport https://github.com/dhis2/tracker-capture-app/pull/125
=> [Dhis2-4176]  Fix bug saving zero attribute value.

components/home/search/search-controller.js
https://jira.dhis2.org/browse/DHIS2-4844
=> Fix for option lists showing as code instead of name in search

components/dataentry/dataentry-controller.js, components/dataentry/event-details.html, components/registration/registration-controller.js
- This has already been done in stages displayed during registration, but will also now be done on the Tracker dashboard.
- Improved the function for setting the date by using getToday from DateUtils.
- https://jira.dhis2.org/browse/DHIS2-4409
=> Report date is set on focus

components/dataentry/dataentry-controller.js, components/dataentry/inner-form.html, components/dataentry/section-inner-form.html
The user can now select to validate on COMPLETE or UPDATE.
DHIS2-4247
Also requires merging: https://github.com/dhis2/d2-tracker/pull/26
=> New validation strategy

components/enrollment/enrollment-controller.js, components/registration/registration-controller.js
https://jira.dhis2.org/browse/DHIS2-4868
Fixed issue with attributes being disabled and page not updating when "Enroll" button is clicked.
=> Enrollment fix

components/dashboard/dashboard-controller.js, components/dashboard/dashboard.html, components/dataentry/compare-form.html, components/dataentry/dataentry-controller.js, components/dataentry/default-form.html, components/dataentry/event-layout.html, components/home/home-controller.js, components/home/home.html, components/home/search/search.html, core/tracker-capture.js, styles/style.css
- Ability to add icons.
- Ability to add colour.
DHIS2-4937 (https://jira.dhis2.org/browse/DHIS2-4937)
=> Icons and colour for meta-data objects

components/dataentry/dataentry-controller.js, components/dataentry/event-layout.html
https://jira.dhis2.org/browse/DHIS2-5024
https://jira.dhis2.org/browse/DHIS2-4893
=> Tracker Stages Chronological Order

components/dashboard/dashboard-controller.js
https://jira.dhis2.org/browse/DHIS2-5324
NOTE: This should **not** be merged before 2.31 is released.
=> Fix for DHIS-5324

components/dataentry/dataentry-tabular-layout.html
Do **NOT** merge until 2.31 is released.
=> Fix for DHIS-5424

components/teiadd/tei-add-controller.js
- https://jira.dhis2.org/browse/DHIS2-5509
=> Fix for DHIS2-5509

components/relationship/relationship.html, core/tracker-capture.js
- https://jira.dhis2.org/browse/DHIS2-4811
=> Relationship display fixes - DHIS2-4811

components/registration/registration-controller.js, components/registration/registration.html
https://jira.dhis2.org/browse/DHIS2-5838
=> Multi click enrollment fix

components/relationship/relationship-controller.js, components/relationship/relationship.html, core/tracker-capture.js, i18n/i18n_app.properties, scripts/services.js
- Events that are linked to a TEI are now displayed in the relationship widget.
- If you click the relationship you are redirected to the capture app and the event will be displayed.
=> Events linked to a TEI is now displayed in the relationship widget

components/home/search/search-controller.js
(cherry picked from commit 633999ce465427d8c7c3cdde83a11fb530a5ecbd)
=> fix: DHIS2-7659 wrong id in duplicate deletion

components/registration/registration-controller.js
Added null check. Fixed error where TEType attributes did not get disabled, even when they where generated or assigned.
=> fix: [DHIS2-7923] null check and logical error

components/home/search/search-controller.js, components/registration/processRegistration.js, scripts/services.js
- remove non-searching attributes from request
- show only attributes with displayInList
=> fix: DHIS2-8317 frontend updates

components/report/program-summary-controller.js
Added null checking that prevents crash
=> fix: [DHIS2-8662] program summary report crash

components/teiadd/tei-add-controller.js
…oller(add relationship modal)
=> fix: [DHIS2-8670] save geometry when storing new TEI from relationship controller

components/teiadd/tei-add-controller.js, scripts/services.js
Use api/relationships for posting new relationships.
=> fix: [DHIS2-9335] allow multiple browser tabs to post relationships for the same TEI

components/dataentry/dataentry-controller.js
Backport of https://github.com/dhis2/tracker-capture-app/pull/1031 into ``v34``
=> fix: Do not override currentStage on each iteration

components/dataentry/compare-form.html, components/dataentry/event-details.html, components/dataentry/modal-default-form.html, components/dataentry/new-event.html, components/dataentry/referral-modal.html, components/dataentry/table-entry-form.html, components/enrollment/enrollment.html, components/home/lists/custom-workinglist.html, components/home/search/search.html, components/registration/default-registration-form.html, components/registration/enrollment-dates-form.html, components/report/overdue-events.html, components/report/report-form.html, components/report/upcoming-events.html, d2-tracker/templates/age-input.html, d2-tracker/templates/date-time-input.html
Was not able to reproduce problem locally, and have thus not been able to test that the fix actually works. But this _should_ to the trick..
Added autocomplete="off" to all elements using d2-date
=> fix: Remove autocomplete on date

components/dataentry/dataentry-controller.js
=> fix: update CurrentSelection whenever an event is added or removed

components/registration/registration-controller.js, d2-tracker/dhis2.angular.controllers.js, d2-tracker/dhis2.angular.directives.js
The second commit is not really a part of the fix - could be made into a separate PR if that's preferred.
=> fix: [DHIS2-10081] make it possible to delete polygons from focus area instances

components/home/lists/lists-controller.js
The list was sorted in a different thread after tildelte brukere was added. Need to run the code in the correct thread, depending on which program is active.
Fixes [SMITTE-198](https://ksfiks.atlassian.net/browse/SMITTE-198)
=> fix: Add tildelt bruker after sorting

ks_patches/import_event_to_list.js, scripts/services.js
When submitting a list of TEIs, we always expect a non-paged list with events for all the teis.
=> fix: Get all events for arbeidsliste

components/report/program-statistics.html
Shows a message saying "Empty" if a pie chart is empty.
The pie charts have also been centered.
=> feat: [DHIS2-12040] empty pie chart message

components/registration/registration-controller.js, scripts/services.js
Removed an IDBObjectStore console log error.
Made it possible to create more than one enrollment per TEI in the same program (provided the program allows it).
Fixed a problem which prevented a newly created enrollment from showing up in the enrollment widget.
=> fix: [DHIS2-9345] issues with creating new enrollment

core/tracker-capture.js, scripts/services.js
Forward port of https://github.com/dhis2/tracker-capture-app/commit/1c09ff6754c4aa69ef08efd046f5d46f0ff731d8
=> fix: [DHIS2-11529] don't crash if a program doesn't have assigned orgUnits

components/messaging/messaging-controller.js, ks_patches/create_notification_for_sms.js, scripts/services.js
* Adds note after sending SMS
* Shows in notification that note has been added
* Clears phone number and message after sending
=> feat: Add note after sending SMS

components/dashboard/dashboard-controller.js, components/registration/default-registration-form.html, components/registration/registration-controller.js, components/registration/registration.html
* fix: don't show "enrollment dates" form in the profile widget
* fix: flash of registration buttons in profile widget
* fix: empty profile widget when no program is selected
=> fix: [DHIS2-12527] various errors in the profile widget

d2-tracker/dhis2.angular.services.js, d2-tracker/dhis2.d2GS1DataMatrix.js
Added support for d2:extractDataMatrixValue(key, dataMatrixText) as described in the epic: https://jira.dhis2.org/browse/DHIS2-12353
The javascript code is based on the backend java rule engine implementation built in this ticket: https://jira.dhis2.org/browse/DHIS2-12364
=> feat: [DHIS2-12365] add d2:extractDataMatrixValue

core/tracker-capture.js, d2-tracker/dhis2.angular.services.js, scripts/services.js
Also inserted missing headers in indicator widget.
=> fix: [DHIS2-12188] filter program indicators by displayInForm=true

d2-tracker/dhis2.angular.services.js
Correction for https://github.com/dhis2/tracker-capture-app/pull/1409
=> fix: remove RulesFactory from list of dependencies

core/tracker-capture.js, package.json, scripts/services.js
Will also download up to 1000 organisation units up-front during initialisation.
=> perf: [DHIS2-11438] download and cache organisation units on demand

d2-tracker/dhis2.angular.services.js
Ported Capture app's recently improved expression parser.
=> fix: [DHIS2-12696] allow complex expressions in d2-function arguments

components/enrollment/enrollment-controller.js, components/enrollment/enrollment.html, components/registration/enrollment-dates-form.html, components/registration/registration-controller.js, components/teiadd/tei-add-controller.js, d2-tracker/dhis2.angular.services.js
- Check that the dates are correctly formatted
- Check whether future date restriction has been violated
=> fix: [DHIS2-11080] validate manually typed enrollment dates and incident dates

components/registration/default-registration-form.html, components/registration/registration-controller.js, components/teiadd/tei-add-controller.js, core/tracker-capture.js, d2-tracker/dhis2.angular.services.js, scripts/services.js
Organise TEAs into sections if a TEA form is defined for a given program.
Use the original layout otherwise.
=> feat: [DHIS2-8210] TEA sections in TEI registration forms

core/tracker-capture.js, d2-tracker/dhis2.angular.services.js, scripts/services.js
Program rule variables type Yes/No should distinguish between No/false and no selection.
=> fix: [DHIS2-13889] distinguish between "No/false" and empty selection

d2-tracker/templates/coordinate-input.html
Only custom forms are affected by this fix.
=> fix: [DHIS2-13145] enable coordinate selection button in profile widget

components/dataentry/compare-form.html, components/dataentry/dataentry-controller.js, components/dataentry/default-form.html, components/dataentry/section-inner-form.html, components/registration/registration-controller.js
Created a new object for looking up **program stage specific DE settings**.
Note that there are a few other settings of this kind besides "Compulsory", e.g. "Allow provided elsewhere", "Display in reports".
I confirmed that the latter needs a similar structure to function properly when a DE appears in multiple program stages.
I have decided not to cover them in this patch however, since they seem of less importance than the "Compulsory" setting, in addition to being out of scope of the referenced JIRA issue.
=> fix: [DHIS2-7778] program stage-wise compulsory DE setting

scripts/services.js
See issue description in [Jira](https://dhis2.atlassian.net/browse/DHIS2-14266)
=> fix: [DHIS2-14266] prevent period skipping for new periodic event

scripts/services.js
- Error in the logic for filtering occupied periods.
- `dummyEvent.periodOffset` and `dummyEvent.hasFuturePeriod` is defined although there are no available periods.
=> fix: [DHIS2-14266] minor corrections in the periodic events-code

d2-tracker/dhis2.angular.services.js
The relevant application of the code changes happens in [dataentry-controller.js](https://github.com/dhis2/tracker-capture-app/blob/39ad51a517e3164c4ec4ba92982e723c910e4124/components/dataentry/dataentry-controller.js#L475).
=> fix: [DHIS2-14190] assign null instead of non-existing option

d2-tracker/dhis2.angular.services.js, index.ejs
Jira issue: [BETA-77](https://dhis2.atlassian.net/browse/BETA-77)
The reported problem is caused by a hard coded file name with wrong spelling.
[BETA-77]: https://dhis2.atlassian.net/browse/BETA-77?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: [BETA-77] file name correction

components/dashboard/dashboard-controller.js
This reverts commit cd1708eba881a677a54caffbd89db28d92a9a95c.
=> Revert "fix: [DHIS2-14599] adapt to the new response format of /potentialDuplicates (#1698)"

components/dashboard/dashboard-controller.js
This reverts commit 9ab9faec7f70f0ae990a471f1a03cd09808a38cc.
=> Revert "fix: [DHIS2-14599] adapt to the new response format of /potentialDuplicates (#1697)"

components/dashboard/dashboard-controller.js
This reverts commit 2d915bc548ea0956a7299277de306165663cd831.
=> Revert "fix: [DHIS2-14599] adapt to the new response format of /potentialDuplicates (#1699)"

d2-tracker/dhis2.angular.services.js
[DHIS2-15464](https://dhis2.atlassian.net/browse/DHIS2-15464)
[DHIS2-15464]: https://dhis2.atlassian.net/browse/DHIS2-15464?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: [DHIS2-15464] d2:right on numerical strings

components/dataentry/compare-form.html, components/dataentry/table-entry-form.html
https://dhis2.atlassian.net/browse/DHIS2-15521
=> fix: [15521] translated form name on data elements

d2-tracker/dhis2.angular.directives.js
@superskip This is a minor fix for a d2 coordinate validation can review it.
=> Minor validation fix on d2map
