dhis2/tracker-capture-app

components/dataentry/dataentry-controller.js

This code was not working when the ouDates was not specified: The
$scope.model.ouDates was present in the model, but
$scope.model.ouDates.startDate and $scope.model.ouDates.endDate was
undefined.
At the same time $scope.selectedProgram.expiryPeriodType was undefined.
This caused a legal date to be dismissed by the saving mechanism.

Fixed too strict validation

---

components/registration/registration-controller.js

Enrolling TEI into several programs using "Add new" button did not work before this fix. Pressing the "Add new" button would earlier give the following error:
>TypeError: Cannot read property '0' of undefined
>at registration-controller.js:319
>at angular.js:13248
>at n.$eval (angular.js:14466)
>at n.$digest (angular.js:14282)
>at n.$apply (angular.js:14571)
>at l (angular.js:9698)
>at M (angular.js:9888)
>at XMLHttpRequest.F.onload (angular.js:9829)
This has been fixed and enrolling TEI to a program is now possible.

Fixed bug where you were not able to enrol a TEI to a new program

---

components/registration/default-registration-form.html

- The bug occurred when you edited an attribute with a warning message under it. Once value was corrected and you pressed tab the cursor would go to the close button on the warning before removing the warning, making the cursor disappear.
- Fixed the bug by making the close warnig button untabbable with the tabindex attribute.
**Result:**

Fixed bug where cursor would disappear

---

index.ejs
scripts/ng-csv.js
scripts/trackerCaptureModule.js

- Calls for the ng-csv script was present without the script being there.
- Added the ng-csv.js script and made sure it was imported.
**overdue-events.html:**
```html
<button type="button" 
class="btn btn-success small-horizontal-spacing" 
ng-csv="generateReportData()"
csv-header="generateReportHeader()"
filename="overdueEvents.csv">
{{'excel_export'| translate}}
</button>
```
_ng-csv and csv-header are both from the ng-csv.js script._ 
**Result:**

Fixed CSV export not working for Upcoming and Overdue Events

---

components/profile/profile-controller.js
components/registration/registration-controller.js
components/registration/registration.html
i18n/i18n_app.properties

https://jira.dhis2.org/browse/DHIS2-1029
Before the warning message was the same as if you would cancel registering a new TEI. It is now changed to:
> Are you sure you want to cancel editing of this profile?
Instead of:
> Are you sure you want to cancel this registration?
The improvement gives a clearer and more understandable warning to the user when he wants to cancel editing a profile in the dashboard.

Added different warning when canceling editing a profile on the dashboard

---

components/dataentry/dataentry-controller.js
components/dataentry/section-inner-form.html
components/registration/default-registration-form.html

- Before: When the "_Date in Future_" checkbox was checked the data element would still not allow the future date to be set.
- Now: Once checked the data element allows dates to be set in future.
- Why: The **allowFutureDate** attribute is updated in a different place. So the system would check against an old value that would not be updated when the checkbox was checked.

Future date fix

---

components/dataentry/event-details.html

https://jira.dhis2.org/browse/DHIS2-2317
- Removed maxDate, because it is not needed.
- Changed minDate to current day, because you would not want a user to reschedule an event back in time.

Fix for not being able to reschedule events to future dates.

---

components/registration/enrollment-dates-form.html
components/teiadd/tei-add-controller.js

https://jira.dhis2.org/browse/DHIS2-2090
- Fixed bug where enrollment date allowed future date when registering a new TEI in relationship widget.
- Fixed bug where program rules would not work when registering a new TEI through the relationship widget.

Relationship bug fixes

---

components/dataentry/dataentry-controller.js

Steps to reproduce:
- Create tracker program
- Set ``openAfterEnrollment`` to multiple program stages in the same tracker program
- Open Tracker Capture with Tabular Data Entry Widget and visit the new tracker program
- See that the last program stage with ``openAfterEnrollment`` property is selected
Expected behavior:
- The first program stage with ``openAfterEnrollment`` property should be selected (same behavior as Android app)
Solution:
- Before overriding ``currentStage`` in the state, check if it has already been defined in a previous iteration of the loop

Do not override currentStage on each iteration

---

components/home/home-controller.js
components/relationship/relationship-controller.js

Fixed so older indexes is not concidered for a cluster. 
If more than one contact event falls in the cluster date range, only concider the first one when determining contact date.
Removed log noise from another change with a null check.

V34 ks cluster updates

---

components/relationship/relationship-controller.js

Add null check to prevent crash when contact does not have a date within the boundaries, and there is an end date set.
Fix indexes that has onset date outside the boundaries, so they will show up under contacts - with no contact date.
Add null check in unlelated function isDuplikatSjekk, to avoid log noise.

fix: cluster logic

---

components/registration/default-registration-form.html

Use ng-if instead of ng-show to remove the Prøvesvar-button from the DOM. This button caused problems with the return button in cases it was hidden (like in registration form).
Fixes SMITTE-153

fix: Do not get prøversvar on return key in registration

---

package.json
yarn.lock

Dep mgmnt to use latest version of d2-tracker. 
Actual change here: https://github.com/dhis2/d2-tracker/commit/226de5050475b48ba6577eb524e05a36040f4d32

fix: [DHIS2-11403] dep mgmnt to include bugfix

---

core/tracker-capture.js
manifest.webapp
scripts/services.js

This fixes a critical issue which would cause NO programs to be available if ANY programs did not have any assigned org units.  Discovered by the team in Ghana in 2.36.3, fixed with a hotfix build of Tracker Capture including these changes.

fix: (2.36) don't crash if a program doesn't have assigned orgUnits [DHIS2-11529]

---

components/naerkontakt_import/naerkontakt-import.html
scripts/app.js

If the user is logged out from Fiks, the html files will not be acceptable. This is a problem, as the template html for the error modal is lazy loaded.
We solve this by putting the templates in cache on startup.

feat: Show error message even if logged out of Fiks

---

components/dataentry/dataentry-controller.js
components/rulebound/rulebound-controller.js
scripts/services.js

By using `$scope.$watch` on `scope.currentEvent.status`, the rules engine will automatically be triggered when the event status changes into _any_ new value, which I believe is what we generally would want to happen.

fix: [DHIS2-7869] display rule effects in feedback widget

---

components/registration/default-registration-form.html
components/registration/registration-controller.js

Previous behavior was that warnings/errors were only shown under form fields that had been recently edited or submitted.
This PR extends this list of conditions to include any non-empty fields as well.

fix: [DHIS2-13617] show warnings and errors on non-empty fields

---

components/dataentry/new-event-controller.js

When $scope.periodOffset is undefined the period change action fails because for example undefined + 1 is NaN where as 1 is the expected result.

fix: [DHIS2-14265] period change when periodOffset undefined

---

d2-tracker/dhis2.angular.services.js
index.ejs
vendor/jquery.calendars.package-1.2.1/jquery.calendars-nb.js
vendor/jquery.calendars.package-1.2.1/jquery.calendars.picker-nb.js

Features a couple of questionable solutions:
- Introduces an identical array in two different files
- Renames the Norwegian translation files ('no' -> 'nb')

fix: [DHIS2-14596] use English as fallback in date picker

---

scripts/services.js

Fixes a detail that was missed in [DHIS2-9190](https://dhis2.atlassian.net/browse/DHIS2-9190)
[DHIS2-9190]: https://dhis2.atlassian.net/browse/DHIS2-9190?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: [DHIS2-15500] use `displayFormName` instead of `formName`

---

components/dataentry/dataentry-controller.js

If multiple "Prevent adding new events to stage" actions are targeting the same program stage, then the stage should be blocked whenever at least one of these actions is in effect. Currently these actions are handled such that the stage gets blocked or unblocked depending on the `inEffect` state of the *last processed* "Prevent adding new events to stage" action.

fix: [DHIS2-17301] prevent adding event to program stage bug
